ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=GPIO engine driver
endef

ifndef USEFILE
USEFILE=$(PROJECT_ROOT)/gpio.use
endif

LIBS += drvrS

NAME=gpio-xzynq
-include $(PROJECT_ROOT)/roots.mk

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

