ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

ifndef IOPKT_MK
IOPKT_MK= ../../../../../io-pkt.mk
endif
-include $(IOPKT_MK)

ifndef IOPKT_ROOT
IOPKT_ROOT:=../../../../../io-pkt
endif

include ../../../prodroot_pkt.mk

EXTRA_INCVPATH+= $(IOPKT_ROOT)/sys $(IOPKT_ROOT)/sys/sys-nto $(IOPKT_ROOT)/lib/socket/public

ifdef CONFIG_PMM
LIBS = netdrvrS drvrS cacheS pmm-xzynq
else
LIBS = netdrvrS drvrS cacheS
endif

NAME = devnp-$(PROJECT)

#treat warning as error
ifdef CONFIG_PMM
CCFLAGS+=	-Werror -DCONFIG_PMM
else
CCFLAGS+=	-Werror
endif

USEFILE=$(PROJECT_ROOT)/$(NAME).use

define PINFO
PINFO DESCRIPTION=XZYNQ Ethernet controller GEM
endef


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk

